<a href="https://colab.research.google.com/github/Fab-Gaurav/Plants-Species/blob/main/Plant's_Species.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Importing Libraries**

Starting with importing some of the Libraries been using in this:

In [ ]:
import pandas as ps
import numpy as np

##**Exploring the Data**

I am using **IRIS** the classical dataset in machine learning and statistics.
It is included in scikit-learn in the datasets module and we can load it by calling the load_iris function.

In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

The iris object that is returned by load

-iris is a Bunch object, which is very simple to adictionary. It contains keys and values :

In [ ]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Accessing the values present at a particular point(**DESCR**)

In [ ]:
print(iris_dataset['DESCR'][:193] + "\n......")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
......


Moving onto the "**target_name**" which contains the species of flower that we want to predict and the values present over it.

In [ ]:
print("Target names: ()".format(iris_dataset['target_names']))

Target names: ()


Moving onto the "**feature_name**" which gives the description of each feature it includes the 'sepal length'(cms).

In [ ]:
print("Feature names: \n{}".format(iris_dataset['feature_names']))

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Extracting the data in NumPy array:

In [ ]:
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


Four measurement value taken for each flower using "shape" :

In [ ]:
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


Features value of first five samples :

In [ ]:
print("First five columns of the data:\n{}".format(iris_dataset['data'][:5]))

First five columns of the data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Now we get to know which column represent which feature.

Moving onto the last key ie. "**target key**" that contains the species of each flowers that were measured as NumPy array.

In [ ]:
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


Getting the shape of the "target key"

In [ ]:
print("Shape of target: {}".format(iris_dataset['target'].shape))

Shape of target: (150,)


Entire value of the "target array"

In [ ]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


From this we get to know by the iris['target_names'] array :
0 maeans sentosa,
1 means versicolor and
2 means virginica

##**Traning and Testing Data**:
Now lets see what our model had learn till now and checking the accuracy.

Splitting the dataset into traning and testing with "**sklearn**" by parameters :

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

Seeing the shape of the data :

In [ ]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


##**Inspecting the Data**:

K-Neighbors Classifier Model

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

Training the model using "**fit**" :

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

##**Making Predictions**

Testing the model at a particular data point :

In [ ]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


Making prediction by calling the predict method of knn obkect :

In [ ]:
prediction = knn.predict(X_new)

print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


##**Evaluating the Model**

Testing the model on the test dataset :

In [ ]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


Checking wheather the actual prediction value correct or not :

In [ ]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158
